# -*- coding: utf-8 -*-
"""Text Vectorization and Similarity Search using Sentence Transformers and FAISS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JgTYT1KLqEhiEniW4pAI1sl_-TrhWi4o
"""

# Install necessary libraries
!pip install transformers sentence-transformers faiss-cpu

# Import necessary libraries
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

# Load the pre-trained model
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')

# Sample texts
texts = [
    "This is an English text.",
    "Este es un texto en español.",
    "Ceci est un texte en français.",
    "Dies ist ein deutscher Text.",
    "これは日本語のテキストです。",
    "这是中文文本。"
]

# Encode texts into vectors
vectors = model.encode(texts)

# Create a FAISS index
dimension = vectors.shape[1]  # dimension of the vectors
index = faiss.IndexFlatL2(dimension)

# Add vectors to the index
index.add(vectors)

# Store vectors with their corresponding texts
vector_text_mapping = {i: text for i, text in enumerate(texts)}

# Query the vector database
def query_database(query, top_k=3):
    query_vector = model.encode([query])
    distances, indices = index.search(query_vector, top_k)
    results = [(vector_text_mapping[idx], distances[0][i]) for i, idx in enumerate(indices[0])]
    return results

# Example query
query = "This is a text in English."
results = query_database(query)

"""

### Interpretation

- **High Similarity**: The result "This is an English text." is very similar to the query "This is a text in English." This is reflected by the low distance score, indicating the model successfully identified a semantically similar text in the database.
  
- **Low Similarity**: The other results "这是中文文本。" (Chinese text) and "これは日本語のテキストです。" (Japanese text) have much higher distance values, indicating they are not semantically similar to the query text.

"""

# Print the results
print(f"Query: {query}\n")
for result, distance in results:
    print(f"Result: {result}, Distance: {distance}")